{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rag.fullname" . }}-data
  labels:
    {{- include "rag.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.persistence.data.storageClass }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
---
{{- if .Values.persistence.hfCache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rag.fullname" . }}-hf-cache
  labels:
    {{- include "rag.labels" . | nindent 4 }}
spec:
  accessModes: [ReadWriteOnce]
  {{- if .Values.persistence.hfCache.storageClass }}
  storageClassName: {{ .Values.persistence.hfCache.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.hfCache.size }}
{{- end }}
